version: 0.2

phases:
  install:
    commands:
      - echo Installing Serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install


  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the serverless framework starting
      - sls deploy -v -s $ENV_NAME

  post_build:
    commands:
      - echo Deployment Completed on `date`  
    
